- hosts: all
  become: yes

  roles:
    - Stouts.timezone
    - franklinkim.environment
    - matti.goodstuff
  vars:
    timezone_timezone: Europe/Helsinki
    #timezone_dependent_services: [rsyslog, apache2, sendmail]
    environment_config:
      - { name: LC_ALL, value: en_US.UTF8 }
